### ISSUE TITLE
关于ImagePager跳转到指定界面？

### ISSUE THREAD

**Issue by JonsonBob** [jvziyaoyao/scale#40]
大佬你好！请问我是用如下代码，我应该怎么使用CurrentIndex跳转到指定的图片页面呢？
ImagePager(
            modifier = Modifier.fillMaxSize(),
            pagerState = rememberZoomablePagerState { previewList.size },
            detectGesture = PagerGestureScope(onTap = {
                isToolbarVisible = !isToolbarVisible
                if (isToolbarVisible) resetAutoHide() else autoHideJob?.cancel()
                onImageClick()
            }),
            imageLoader = { index ->
                val painter = rememberCoilImagePainter(
                    image = previewList[index].filePreviewUrl, previewList[index].fileUrlHeaders
                )
                val pair = remember { mutableStateOf<Pair<Any?, Size?>>(Pair(null, null)) }
                LaunchedEffect(painter) {
                    delay(1000)
                    pair.value = Pair(painter, painter.intrinsicSize)
                }
                return@ImagePager pair.value
            },
//            pageDecoration =
        )
期待大佬回复

**Comment by jvziyaoyao** [comment]
@JonsonBob  与HorizontalPager到用法差不多
```
val pagerState = rememberZoomablePagerState { previewList.size }
// 跳转到第二页
pagerState.scrollToPage(2)
// 动画跳转到第二页
pagerState.animateScrollToPage(2)
```
